# Generated by Django 2.2.10 on 2020-12-14 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='follows',
            name='created_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='photos',
            name='created_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
